logging:
  use_wandb: false
  save_dir: "D:/Research/Mathematics/SYSU_GBU/6_Lectures/0_MachineLearning/2_Final_homework/2_code/checkpoints"

model:
  name: UNet3D
  # name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcl
  # initial number of feature maps
  f_maps: 24
  # number of groups in the groupnorm
  num_groups: 3
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
# loss function to be used during training
loss:
  name: BCEDiceLoss
  alpha: 1
  # a target value that is ignored and does not contribute to the input gradient
  # ignore_index: null
  # skip the last channel in the target (i.e. when last channel contains data not relevant for the loss)
  # skip_last_target: true
optimizer:
  # initial learning rate
  lr: 0.0002
  # weight decay
  weight_decay: 0.000001
lr_scheduler:
  name: ReduceLROnPlateau
  # make sure to use the 'min' mode cause lower AdaptedRandError is better
  mode: min
  factor: 0.5
  patience: 30
training:
  grad_clip: 100
  # model with lower eval score is considered better
  eval_score_higher_is_better: False
  # path to the checkpoint directory
  checkpoint_dir: CHECKPOINT_DIR
  # path to latest checkpoint; if provided the training will be resumed from that checkpoint
  resume: null
  # path to the best_checkpoint.pytorch; to be used for fine-tuning the model with additional ground truth
  pre_trained: null
  # how many iterations between tensorboard logging
  log_after_iters: 50
  # max number of epochs
  max_num_epochs: 50
# Configure training and validation loaders
loaders:
  # 
  dataset: 
    name: RawMSDLungPatchDataset
    base_path: E:\2_Project_Data\3_SYSU_MLLecture_final_medical_segmentation_lung_ca\0_original\Task06_Lung_hdf5
    json_path: E:\2_Project_Data\3_SYSU_MLLecture_final_medical_segmentation_lung_ca\0_original\Task06_Lung_hdf5\dataset.json
  # how many subprocesses to use for data loading
  # set it to ZERO if you're on WINDOWS platform
  num_workers: 4
  batch_size: 2
  # path to the raw data within the H5
  raw_internal_path: raw
  # path to  the label data within the H5
  label_internal_path: label
  # apply random shifting and scaling of the patches; value of 20 mean that patches may shrink/stretch by 20px in each dimension
  random_scale: 20
  # random scale execution probability; since random scale is quite slow for 3D data, we set it to 0.1
  random_scale_probability: 0.1
  # compute global dataset statistics (mean, std) for Standardize transformer
  global_normalization: true
  # configuration of the train loader
  train:
    # path to the training datasets
    file_paths:
      - PATH_TO_TRAIN_DIR

    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: FilterSliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [32, 128, 128]
      # train stride between patches
      stride_shape: [16, 64, 64]
      # minimum volume of the labels in the patch
      threshold: 0.0001
      # probability of accepting patches which do not fulfil the threshold criterion
      slack_acceptance: 0.01

    transformer:
      raw:
        - name: Standardize
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY plane due to anisotropy
          axes: [[2, 1]]
          angle_spectrum: 45
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
        - name: ToTensor
          expand_dims: true
      label:
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          # rotate only in ZY plane due to anisotropy
          axes: [[2, 1]]
          angle_spectrum: 45
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
        - name: StandardLabelToBoundary
          # append original ground truth labels to the last channel (to be able to compute the eval metric)
          append_label: true
        - name: ToTensor
          expand_dims: false

  # configuration of the val loader
  val:
    # path to the val datasets
    file_paths:
      - PATH_TO_VAL_DIR

    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: FilterSliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [32, 128, 128]
      # train stride between patches
      stride_shape: [16, 64, 64]
      # minimum volume of the labels in the patch
      threshold: 0.0001
      # probability of accepting patches which do not fulfil the threshold criterion
      slack_acceptance: 0.01

    # data augmentation
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
      label:
        - name: StandardLabelToBoundary
          append_label: true
        - name: ToTensor
          expand_dims: false